name: KeepItems
version: '${project.version}'
main: yt.sehrschlecht.keepitems.KeepItems
api-version: 1.14
authors: [ sehrschlechtYT ]
description: Adds filters that allow to keep or remove various items in inventory upon death.
commands:
  keepitems:
    permission: keepitems.admin
    aliases:
      - keep-items
    description: Reloads the KeepItems plugin.
permissions:
  keepitems.admin:
    default: op
    description: Makes the command /keepitems executable.