name: KeepItems
version: '${project.version}'
main: yt.sehrschlecht.keepitems.KeepItems
api-version: 1.14
authors: [ sehrschlechtYT ]
description: Keeps various items in the inventory upon death.
commands:
  keepitems:
    permission: keepitems.admin
    aliases:
      - keep-items
    description: The admin command for KeepItems.
permissions:
  keepitems.admin:
    default: op
    description: Makes the command /keepitems executable.